# Use Python 3.13 image
FROM python:3.13-slim

# Install system dependencies for Fiona and GDAL
RUN apt-get update && apt-get install -y \
    gdal-bin libgdal-dev gcc g++ \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy and install requirements
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project files
COPY . .

# Expose port and start gunicorn
EXPOSE 8000
CMD ["gunicorn", "LofinAppStore.wsgi:application", "--bind", "0.0.0.0:8000"]
